spring.application.name=aether_back_spring

spring.security.user.name=user
spring.security.user.password=1234

# jwt
jwt.key=f15e820e5f40e68774e4ca58fc86bbd8e08ab11d13e97b058dd59f15cb74ba7a290f0ffd557ddad6ba4df7323c8d0a23b2868598c42d0b89c38ebdb98d8ce303

# redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Datasource
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=hs
spring.datasource.password=1234

# oauth
spring.profiles.include=oauth