spring.application.name=aether-back-auth

# eureka - client
server.port=8082

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# oauth, cloud
spring.profiles.include=oauth, cloud, secret