spring.application.name=aether_back_spring

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=1234

spring.security.user.name=user
spring.security.user.password=1234

# oauth ??? ?? (application-oauth.properties?? Id,????,scope ???)
spring.profiles.include=oauth