name: "Deploy"
description: "배포 관련 작업"
labels: ["deploy"]
body:
- type: textarea
  attributes:
    label: 📄 설명
    description: 작업에 대한 설명
  validations:
    required: true
- type: textarea
  attributes:
    label: ✅ 작업할 내용
    description: 할 일을 체크박스 형태로 작성
  validations:
    required: true
- type: textarea
  attributes:
    label: 🙋🏻 참고 자료
    description: 참고 자료가 있다면 작성
