name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # 1. Java 21 세팅
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    
    # 2. SpringBoot 애플리케이션 빌드
    - name: Build with Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: clean bootJar

    # 3. Docker 이미지 빌드
    - name: Docker Image Build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/aether_back_spring .

    # 4. DockerHub 로그인
    - name: DockerHub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # 5. DockerHub 이미지 push
    - name: DockerHub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/aether_back_spring

  run-docker-image-on-ec2:
    # build-docker-image (위)과정이 완료되어야 실행됨
    needs: build-docker-image
    runs-on: self-hosted

    steps:
      # 1. 최신 이미지를 pull 받음
      - name: Docker pull
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/aether_back_spring
      
      # 2. 기존 컨테이너 중지
      - name: Docker stop Container
        run: sudo docker stop $(sudo docker ps -q) 2>/dev/null || true

      # 3. 최신 이미지를 컨테이너화하여 실행
      - name: Docker run new Container
        run: sudo docker run --name aether_back_spring --rm -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/aether_back_spring

      # 4. 미사용 이미지 정리
      - name: Delete old Docker Image
        run: sudo docker system prune -f
    
